//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.Client.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class AddCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.ContractType")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class AddCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class UpdateCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class UpdateCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUpdatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUpdated {
            get {
                return this.IsUpdatedField;
            }
            set {
                if ((this.IsUpdatedField.Equals(value) != true)) {
                    this.IsUpdatedField = value;
                    this.RaisePropertyChanged("IsUpdated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class RemoveCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class RemoveCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRemovedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRemoved {
            get {
                return this.IsRemovedField;
            }
            set {
                if ((this.IsRemovedField.Equals(value) != true)) {
                    this.IsRemovedField = value;
                    this.RaisePropertyChanged("IsRemoved");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllCustomersRequest", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class GetAllCustomersRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllCustomersResponse", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class GetAllCustomersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Capgemini.Client.CustomerServiceReference.CustomerDto> CustomersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Capgemini.Client.CustomerServiceReference.CustomerDto> Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerRequest", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class GetCustomerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCustomerResponse", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.Service.Message")]
    [System.SerializableAttribute()]
    public partial class GetCustomerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Capgemini.Client.CustomerServiceReference.CustomerDto CustomerDto {
            get {
                return this.CustomerDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDtoField, value) != true)) {
                    this.CustomerDtoField = value;
                    this.RaisePropertyChanged("CustomerDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.capgemini.pl", ConfigurationName="CustomerServiceReference.CustomerService")]
    public interface CustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/AddCustomer", ReplyAction="www.capgemini.pl/CustomerService/AddCustomerResponse")]
        Capgemini.Client.CustomerServiceReference.AddCustomerResponse AddCustomer(Capgemini.Client.CustomerServiceReference.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/AddCustomer", ReplyAction="www.capgemini.pl/CustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.AddCustomerResponse> AddCustomerAsync(Capgemini.Client.CustomerServiceReference.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/UpdateCustomer", ReplyAction="www.capgemini.pl/CustomerService/UpdateCustomerResponse")]
        Capgemini.Client.CustomerServiceReference.UpdateCustomerResponse UpdateCustomer(Capgemini.Client.CustomerServiceReference.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/UpdateCustomer", ReplyAction="www.capgemini.pl/CustomerService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.UpdateCustomerResponse> UpdateCustomerAsync(Capgemini.Client.CustomerServiceReference.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/RemoveCustomer", ReplyAction="www.capgemini.pl/CustomerService/RemoveCustomerResponse")]
        Capgemini.Client.CustomerServiceReference.RemoveCustomerResponse RemoveCustomer(Capgemini.Client.CustomerServiceReference.RemoveCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/RemoveCustomer", ReplyAction="www.capgemini.pl/CustomerService/RemoveCustomerResponse")]
        System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.RemoveCustomerResponse> RemoveCustomerAsync(Capgemini.Client.CustomerServiceReference.RemoveCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/GetAllCustomers", ReplyAction="www.capgemini.pl/CustomerService/GetAllCustomersResponse")]
        Capgemini.Client.CustomerServiceReference.GetAllCustomersResponse GetAllCustomers(Capgemini.Client.CustomerServiceReference.GetAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/GetAllCustomers", ReplyAction="www.capgemini.pl/CustomerService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.GetAllCustomersResponse> GetAllCustomersAsync(Capgemini.Client.CustomerServiceReference.GetAllCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/GetCustomer", ReplyAction="www.capgemini.pl/CustomerService/GetCustomerResponse")]
        Capgemini.Client.CustomerServiceReference.GetCustomerResponse GetCustomer(Capgemini.Client.CustomerServiceReference.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.capgemini.pl/CustomerService/GetCustomer", ReplyAction="www.capgemini.pl/CustomerService/GetCustomerResponse")]
        System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.GetCustomerResponse> GetCustomerAsync(Capgemini.Client.CustomerServiceReference.GetCustomerRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceChannel : Capgemini.Client.CustomerServiceReference.CustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Capgemini.Client.CustomerServiceReference.CustomerService>, Capgemini.Client.CustomerServiceReference.CustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Capgemini.Client.CustomerServiceReference.AddCustomerResponse AddCustomer(Capgemini.Client.CustomerServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.AddCustomerResponse> AddCustomerAsync(Capgemini.Client.CustomerServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public Capgemini.Client.CustomerServiceReference.UpdateCustomerResponse UpdateCustomer(Capgemini.Client.CustomerServiceReference.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.UpdateCustomerResponse> UpdateCustomerAsync(Capgemini.Client.CustomerServiceReference.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public Capgemini.Client.CustomerServiceReference.RemoveCustomerResponse RemoveCustomer(Capgemini.Client.CustomerServiceReference.RemoveCustomerRequest request) {
            return base.Channel.RemoveCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.RemoveCustomerResponse> RemoveCustomerAsync(Capgemini.Client.CustomerServiceReference.RemoveCustomerRequest request) {
            return base.Channel.RemoveCustomerAsync(request);
        }
        
        public Capgemini.Client.CustomerServiceReference.GetAllCustomersResponse GetAllCustomers(Capgemini.Client.CustomerServiceReference.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomers(request);
        }
        
        public System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.GetAllCustomersResponse> GetAllCustomersAsync(Capgemini.Client.CustomerServiceReference.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomersAsync(request);
        }
        
        public Capgemini.Client.CustomerServiceReference.GetCustomerResponse GetCustomer(Capgemini.Client.CustomerServiceReference.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public System.Threading.Tasks.Task<Capgemini.Client.CustomerServiceReference.GetCustomerResponse> GetCustomerAsync(Capgemini.Client.CustomerServiceReference.GetCustomerRequest request) {
            return base.Channel.GetCustomerAsync(request);
        }
    }
}
